Upgrade mPDF to 8.1.X
splitbrain/dokuwiki-plugin-dw2pdf pull request #476
Opened 2023-02-28 20:10 UTC by eduardomozart

Upgrade mPDF to 8.1.X to add support for PHP 8.X as mPDF from DW2PDF supports PHP <= 7.4 (fixes #474).

2023-02-28 21:06 UTC, Klap-in requested changes
Thanks for the update.

Please check the manual patch, and reply it. It ensures the ACL are checked for the images from the wiki.

I observe that mpdf includes its own http client. A nice to have would be to configure it to use the http client of DokuWiki... see also https://mpdf.github.io/configuration/configuration-v7-x.html#http-client 

@splitbrain how do you judge dropping of php7.4 support? I guess it will result in questions..

2023-02-28 21:06 UTC, Klap-in commented on vendor/mpdf/mpdf/src/Tag/Img.php
> -use \dokuwiki\plugin\dw2pdf\DokuImageProcessorDecorator as ImageProcessor;
We did implement a dw2pdf specific imageProcessorDecorator. Unfortunately it had to be done by modifying a file of the mpdf library. Did you test if it can run without this patch? I expect the patch is still needed.
It ensures ACL is respected for pictures.

See history in https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/commits/master/vendor

2023-02-28 21:06 UTC, Klap-in commented on vendor/mpdf/mpdf/src/Tag/Tag.php
> +use Mpdf\Image\ImageProcessor;
We did implement a dw2pdf specific image decorator. Unfortunately had to be done by modifying a file of the mpdf library.

2023-02-28 21:06 UTC, Klap-in commented on vendor/mpdf/mpdf/src/Tag/Tag.php
> +	 * @var \Mpdf\Image\ImageProcessor
We did implement a dw2pdf specific image decorator. Unfortunatey had to be done by modifying a file of the mpdf library.

2023-02-28 21:37 UTC, eduardomozart commented on vendor/mpdf/mpdf/src/Tag/Img.php
> -use \dokuwiki\plugin\dw2pdf\DokuImageProcessorDecorator as ImageProcessor;
I've applied this suggestion into this PR. Thank you!

2023-02-28 21:37 UTC, eduardomozart commented on vendor/mpdf/mpdf/src/Tag/Tag.php
> +	 * @var \Mpdf\Image\ImageProcessor
I've applied this suggestion into this PR. Thank you!

2023-02-28 21:37 UTC, eduardomozart commented on vendor/mpdf/mpdf/src/Tag/Tag.php
> +use Mpdf\Image\ImageProcessor;
I've applied this suggestion into this PR. Thank you!

2023-02-28 21:38 UTC, eduardomozart commented
Thank you. I didn't know that, but I'd noticed that local images wasn't being loaded with a newer mPDF version and was trying to figure out why. Applied your suggestions and now DW2PDF seems to be working as expected.

2023-02-28 23:25 UTC, Klap-in commented
Thanks for patching again. Could you check please why the unit tests did fail? Remarkably, it still throws an error about the decorator..

2023-03-01 00:06 UTC, eduardomozart commented
Those unit tests seems to be failing because mPDF 8.1.4 requires PHP 8, which is the only test that succeeded as expected. It would be great to implement DokuWiki HTTPClient for mPDF, as it would support parameters set at the DokuWiki interface (like Proxy), but I don’t see developing it as a priority because I do not use any of those features right now (most of my bug contributions are related to bugs or features I found myself into our own Wiki environment). As developing isn’t my main function (I’m a SysAdmin), I can get in trouble in my work if I took to much time developing instead of deploying systems and attending our clients.

2023-03-03 21:21 UTC, Klap-in commented
about http client, clear trade-off, thanks for the effort so far. If it would fit you, it would be an opportunity. Therefore, I brought it up. Without is also fine.

Ah, I see now something from composer is blocking it. That would mean for everybody with php7.4 and lower it is not usable. 
Since November 7.4 is also EOL. 

Feels a bit to early to completely not support php7 anymore, but we have also no method to indicate it to the user. Maybe the extension manager should get a way to inform users before installing.

2023-11-07 14:20 UTC, closed without merging